apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-validator
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    name: {{ .Release.Name }}-validator
  ports:
  - name: "4004"
    protocol: TCP
    port: 4004
    targetPort: 4004
  - name: "5050"
    protocol: TCP
    port: 5050
    targetPort: 5050
  - name: "8800"
    protocol: TCP
    port: 8800
    targetPort: 8800
