validator:
  name: "sawtooth-validator"
  image:
    repository: hyperledger/sawtooth-validator
    tag: 1.1
  genesis: false
  config:
    bind: '["component:tcp://eth0:4004", "consensus:tcp://eth0:5050", "network:tcp://eth0:8800"]'
    peering: dynamic
    endpoint: tcp://{{ .Release.Name }}-validator:8800
    seeds: ''
    peers: ""
    scheduler: parallel
    network_public_key: 
    network_private_key:
    minimum_peer_connectivity: 3
    maximum_peer_connectivity: 10
    network: trust
    transactor:
    transaction_signer:
opentsdb:
  url:
  db:
  username:
  password:
poet_engine:
  name: sawtooth-poet-engine
  image:
    repository: hyperledger/sawtooth-poet-engine
    tag: 1.1
rest_api:
  name: sawtooth-rest-api
  image:
    repository: hyperledger/sawtooth-rest-api
    tag: 1.1
  config:
    timeout: 300
    client_max_size: 10485760
settings_tp:
  name: sawtooth-settings-tp
  image:
    repository: hyperledger/sawtooth-settings-tp
    tag: 1.1
block_info_tp:
  name: sawtooth-block-info-tp
  image:
    repository: hyperledger/sawtooth-block-info-tp
    tag: 1.1
poet_validator_registry_tp:
  name: sawtooth-poet-validator-registry-tp
  image:
    repository: hyperledger/sawtooth-poet-validator-registry-tp
    tag: 1.1
persistence:
  enabled: true
  pv:
    name: ""
    path: ""
    capacity: 10Gi
    node: ""
  pvc:
    name: ""
    storage: 10Gi
  storageClass:
    name: "sawtooth-standard"

