apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  validator.toml: |
    bind = {{ .Values.validator.config.bind }}
    peering = {{ .Values.validator.config.peering | quote }}
    endpoint = {{ tpl .Values.validator.config.endpoint . | quote }}
    seeds = {{ .Values.validator.config.seeds }}
{{ if .Values.validator.config.peers }}
    peers = {{ .Values.validator.config.peers }}
{{ end }}
    scheduler = {{ .Values.validator.config.scheduler | quote }}
{{ if .Values.validator.config.network_public_key }}
    network_public_key = {{ .Values.validator.config.network_public_key | quote }}
{{ end }}
{{ if .Values.validator.config.network_private_key }}
    network_private_key = {{ .Values.validator.config.network_private_key | quote }}
{{ end }}
{{ if .Values.validator.config.minimum_peer_connectivity }}
    minimum_peer_connectivity = {{ .Values.validator.config.minimum_peer_connectivity }}
{{ end }}
{{ if .Values.validator.config.maximum_peer_connectivity }}
    maximum_peer_connectivity = {{ .Values.validator.config.maximum_peer_connectivity }}
{{ end }}
{{ if .Values.opentsdb.url }}
    opentsdb_url = {{ .Values.opentsdb.url | quote }}
{{ end }}
{{ if .Values.opentsdb.db }}
    opentsdb_db = {{ .Values.opentsdb.db | quote }}
{{ end }}
{{ if .Values.opentsdb.username }}
    opentsdb_username = {{ .Values.opentsdb.username | quote }}
{{ end }}
{{ if .Values.opentsdb.password }}
    opentsdb_password = {{ .Values.opentsdb.password | quote }}
{{ end }}
    [roles]
    network = {{ .Values.validator.config.network | quote }}
    [permissions]
{{ if .Values.validator.config.transactor }}
    transactor = {{ .Values.validator.config.transactor | quote }}
{{ end }}
{{ if .Values.validator.config.transaction_signer }}
    transactor.transaction_signer = {{ .Values.validator.config.transaction_signer | quote }}
{{ end }}
  rest_api.toml: |
    bind = ["0.0.0.0:8008"]
    connect = "tcp://{{ .Release.Name }}-validator:4004"
    timeout = {{ .Values.rest_api.config.timeout }}
    client_max_size = {{ int64 .Values.rest_api.config.client_max_size }}
{{ if .Values.opentsdb.url }}
    opentsdb_url = {{ .Values.opentsdb.url | quote }}
{{ end }}
{{ if .Values.opentsdb.db }}
    opentsdb_db = {{ .Values.opentsdb.db | quote }}
{{ end }}
{{ if .Values.opentsdb.username }}
    opentsdb_username = {{ .Values.opentsdb.username | quote }}
{{ end }}
{{ if .Values.opentsdb.password }}
    opentsdb_password = {{ .Values.opentsdb.password | quote }}
{{ end }}