apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-settings-tp
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-settings-tp
    spec:
      containers:
      - name: sawtooth-settings-tp
        image: hyperledger/sawtooth-settings-tp:1.1
        command:
        - bash
        args:
        - -c
        - "sawtooth-rest-api -C tcp://{{ .Release.Name }}-validator:4004"