apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  name: {{ .Release.Name }}-rest-api
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-rest-api
        app: sawtooth-rest-api
    spec:
      containers:
      - name: {{ .Values.rest_api.name }}
        image: {{ .Values.rest_api.image.repository }}:{{ .Values.rest_api.image.tag }}
        ports:
        - name: api
          containerPort: 8008
        command:
        - bash
        args:
        - -c
        - "ln -sf /sawtooth-config/rest_api.toml /etc/sawtooth/rest_api.toml; sawtooth-rest-api"
        volumeMounts:
        - name: sawtooth-config
          mountPath: "/sawtooth-config"
      volumes:
      - name: sawtooth-config
        configMap:
          name: {{ .Release.Name }}-config