apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rest-api
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    name: {{ .Release.Name }}-rest-api
  ports:
  - name: "8008"
    protocol: TCP
    port: 8008
    targetPort: 8008
