apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ required "missing pv name" .Values.persistence.pv.name }}
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ required "missing storage class" .Values.persistence.storageClass.name }}
  local:
    path: {{ required "missing pv path" .Values.persistence.pv.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ required "missing pv nodes" .Values.persistence.pv.node }}
