{{ if .Values.persistence.storageClass.create -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: "2019-04-15T08:42:27Z"
  name: {{ required "missing storage class" .Values.persistence.storageClass.name }}
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
{{- end }}