apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-registry-tp
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-registry-tp
      spec:
        containers:
        - name: sawtooth-poet-validator-registry-tp
          image: hyperledger/sawtooth-poet-validator-registry-tp:1.1
          command:
          - bash
          args:
          - -c
          - "poet-validator-registry-tp -C tcp://{{ .Release.Name }}-validator:4004"